### ISSUE TITLE
WARNING: pytables package not found. ioHub functionality will be disabled.

### ISSUE THREAD

**Issue by JensBoelte** [psychopy/psychopy#5876]
Hello,

after upgrading to PsychoPy version 2023.2.1 I keep receiving the following warning when running an experiment:

WARNING: pytables package not found. ioHub functionality will be disabled.

However, the tables library seems to be installed

C:\Program Files\PsychoPy>python -m pip install tables
Requirement already satisfied: tables in c:\program files\psychopy\lib\site-packages (3.6.1)
Requirement already satisfied: numpy>=1.9.3 in c:\program files\psychopy\lib\site-packages (from tables) (1.24.4)
Requirement already satisfied: numexpr>=2.6.2 in c:\program files\psychopy\lib\site-packages (from tables) (2.7.3)

How do I get PsychoPy to recognize that the library tables is installed?

Best wishes Jens

**Comment by peircej** [comment]
I wonder if it's installed but failing to import. Could you try 
`c:\program files\psychopy\python -c 'import tables; print(tables.__version__)' `

**Comment by revatis2** [comment]
I ran into the same issue after updating to v2023.2.2. When I run ```c:\program files\psychopy\python -c 'import tables; print(tables.__version__)'```, I get this:

```ImportError: cannot import name typeDict```

However when I ran ```C:\Program Files\PsychoPy>python -m pip install tables```, it says the requirement was already satisfied, like in the OP's question.

**Comment by JensBoelte** [comment]
Hello

`c:\program files\psychopy\python -c 'import tables; print(tables.__version__)'` gives an error 

`C:\Program Files\PsychoPy>python -c 'import tables'
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal`

`python -c "import tables"` runs (?) but also throws an error 
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\PsychoPy\lib\site-packages\tables\__init__.py", line 99, in <module>
    from .utilsextension import (
  File "tables\utilsextension.pyx", line 169, in init tables.utilsextension
ImportError: cannot import name typeDict`

Best wishes Jens

**Comment by JensBoelte** [comment]
Hello,

I think I could solve this problem. PsychoPy "complains" that the installed numpy-version (1.24.4) is too new and that it needs a numpy version 1.22 or older. Downgrading to this numpy-version gets rid of the warning and pytables are loaded. Notice that pip complains about some dependency conflicts afterwards:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> psychopy 2023.2.2 requires pyparallel; platform_system != "Darwin", which is not installed.
> psychopy 2023.2.2 requires websockets, which is not installed.
> psychopy 2023.2.2 requires xmlschema, which is not installed.
> psychopy 2023.2.2 requires javascripthon>=0.12, but you have javascripthon 0.11 which is incompatible.
> psychopy 2023.2.2 requires pandas>=1.5.3, but you have pandas 1.3.4 which is incompatible.
> psychopy 2023.2.2 requires pillow>=9.4.0, but you have pillow 8.4.0 which is incompatible.
> psychopy 2023.2.2 requires questplus>=2023.1, but you have questplus 2019.4 which is incompatible.

Should I upgrade this libraries as well?

Best wishes Jens

**Comment by peircej** [comment]
We shouldn't need to send numpy all the way back to 1.22 but if I update tables to 3.8 that also seems to fix it so I'm guessing the tables team has spotted the issue and handled it too

**Comment by peircej** [comment]
Regarding the others, yes, I think that's a good idea 👍 
Will have these in place for 2023.2.3

**Comment by kesslerr** [comment]
> We shouldn't need to send numpy all the way back to 1.22 but if I update tables to 3.8 that also seems to fix it so I'm guessing the tables team has spotted the issue and handled it too

Actually, I came across the same problem and error on a Mac. Tables 3.8.0 is installed,and numpy 1.24.4.
