### ISSUE TITLE
StaticComp causing crash

### ISSUE THREAD

**Issue by jeremygray** [psychopy/psychopy#871]
See users list March 11th 2015 "More verbose error report in code generation?". Removing the offending StaticComp solved the problem, but might not always be possible as a solution. This is the actual error:

```
Welcome to PsychoPy2!
v1.82.01
Traceback (most recent call last):
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/builder.py", line 4729, in compileScript
    script = self.generateScript(None) #leave the experiment path blank
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/builder.py", line 4755, in generateScript
    return self.exp.writeScript(expPath=experimentPath)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/experiment.py", line 183, in writeScript
    self.flow.writeCode(script) #write the rest of the code for the components
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/experiment.py", line 1114, in writeCode
    entry.writeMainCode(script)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/experiment.py", line 1223, in writeMainCode
    event.writeFrameCode(buff)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/components/static.py", line 60, in writeFrameCode
    self.writeStopTestCode(buff)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/components/static.py", line 83, in writeStopTestCode
    self.writeParamUpdates(buff)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/psychopy/app/builder/components/static.py", line 101, in writeParamUpdates
    params = routine.getComponentFromName(unicode(compName)).params
AttributeError: 'NoneType' object has no attribute 'params'
```

**Comment by hoechenberger** [comment]
Ugh, facing the very same problem right now. I get this error message every time I set a stimulus to update during a static component (ITI) in another routine, and it has nothing to do with removing or renaming that static component first. As soon as I select to update stimuli during the component, I won't be able to compile the experiment anymore.

**Comment by peircej** [comment]
Yes, I think this is a problem with tracking the existing static components and which other components point to them. We can end up with components pointing to statics that no longer exist.

**Comment by TEParsons** [comment]
ISI now works in JS as of 2022.1.0
