### ISSUE TITLE
psychopyApp.py ffmpeg download problem

### ISSUE THREAD

**Issue by tjwilli58** [psychopy/psychopy#1805]
I my version of PsychoPy 1.90.1, I had to comment out the section in _psychopyApp.py that tries to download ffmpeg:

```
        # if we have imageio then try to download ffmpeg
        try:
            import imageio
            haveImageio = True
        except:
            haveImageio = False
        if haveImageio:
            # download() returns immediately if we have it already
            ffmpegDownloader = threading.Thread(target=imageio.plugins.ffmpeg.download)
            ffmpegDownloader.start()

```

```
Welcome to PsychoPy2!
v1.90.1
Imageio: 'ffmpeg.win32.exe' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error _ssl.c:761: The handshake operation timed out>.Exception in thread Thread-3:
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-3, started 12168)>>
Traceback (most recent call last):


During handling of the above exception, another exception occurred:



```

If I try to do this from spyder, I get something slightly different:
```
imageio.plugins.ffmpeg.download()
Imageio: 'ffmpeg.win32.exe' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error _ssl.c:761: The handshake operation timed out>.
Error while fetching file: <urlopen error _ssl.c:761: The handshake operation timed out>.
Error while fetching file: <urlopen error _ssl.c:761: The handshake operation timed out>.
Error while fetching file: <urlopen error _ssl.c:761: The handshake operation timed out>.
Traceback (most recent call last):

  File "<ipython-input-9-e387883dc4c6>", line 1, in <module>
    imageio.plugins.ffmpeg.download()

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\plugins\ffmpeg.py", line 55, in download
    get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\core\fetching.py", line 121, in get_remote_file
    _fetch_file(url, filename)

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\core\fetching.py", line 177, in _fetch_file
    os.path.basename(file_name))

OSError: Unable to download 'ffmpeg.win32.exe'. Perhaps there is a no internet connection? If there is, please report this problem.

```
I have ffmpeg installed from conda, but imageio is not finding it. I know that I need to set `IMAGEIO_FFMPEG_EXE`, but I haven't figured out the best way to do this in Anaconda. I researching it now.

The code to download ffmpeg is not in _psychopyApp.py in version 1.85.3.
I suppose this is more of a conda or imageio question, but does anyone know of a good way around this?

**Comment by tjwilli58** [comment]
I set IMAGEIO_FFMPEG_EXE to 

> %USERPROFILE%\Anaconda3\Library\bin\ffmpeg.exe

and imageio.plugins.ffmpeg.download() DOES NOT immediately return.  It still tries to download ffmpeg, which fails for me. I think this works better:

```
        # if we have imageio then try to download ffmpeg
        try:
            import imageio
            haveImageio = True
        except:
            haveImageio = False
        if haveImageio:
            if not os.path.exists(imageio.plugins.ffmpeg.get_exe()):
                ffmpegDownloader = threading.Thread(target=imageio.plugins.ffmpeg.download)
                ffmpegDownloader.start()

```

**Comment by peircej** [comment]
Basically the idea here is to fetch ffmpeg at some point before it gets needed by the script. 
What happens when you then run a study that uses moviepy? Does it find ffmpeg and use it correctly? 

On my system, when ffmpeg has been downloaded it then gets used. My sense is that this is a problem between the anaconda distribution and the use of moviepy/imageio. If it is that our method of installation (the direct use of download()) is the problem then we should fix it, but if the problem is that imageio doesn't work well on anaconda then it's for someone else to fix (or a reason not to use anaconda distro).

**Comment by tjwilli58** [comment]
I haven't used moviepy yet. Still learning, I did run the MovieStim.py example. MoveStim2.py and MovieStim3.py gave me errors on python 3.6. One problem was I didn't have opencv installed.

In ffmpeg.download looks for ffmpeg.win32.exe, but conda has ffmpeg installed as ffmpeg.exe in the Library/bin directory. I copied it to ffmpeg.win32.exe, but ffmpeg.download() still didn't find it. I'm not sure why. I didn't see which PATH is used to find ffmpeg.win32.exe. This seems to be a bug in imageio, but it seems to me that checking for the existence of imageio.plugins.ffmpeg.get_exe() is a more reliable test.

```
FNAME_PER_PLATFORM = {
    'osx32': 'ffmpeg.osx',
    'osx64': 'ffmpeg.osx',
    'win32': 'ffmpeg.win32.exe',
    'win64': 'ffmpeg.win32.exe',
    'linux32': 'ffmpeg.linux32',
    'linux64': 'ffmpeg.linux64',
}

```

```
def download():
    """ Download the ffmpeg exe to your computer.
    """
    plat = get_platform()
    if not (plat and plat in FNAME_PER_PLATFORM):
        raise RuntimeError("FFMPEG exe isn't available for platform %s" % plat)
    get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])

```

```
imageio.plugins.ffmpeg.get_exe()
Out[8]: 'C:\\Users\\timothy.j.williams1\\Anaconda3\\Library\\bin\\ffmpeg.win32.exe'

os.environ['IMAGEIO_FFMPEG_EXE']
Out[12]: 'C:\\Users\\timothy.j.williams1\\Anaconda3\\Library\\bin\\ffmpeg.win32.exe'

imageio.plugins.ffmpeg.download()
Imageio: 'ffmpeg.win32.exe' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>.
Traceback (most recent call last):

  File "<ipython-input-13-e387883dc4c6>", line 1, in <module>
    imageio.plugins.ffmpeg.download()

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\plugins\ffmpeg.py", line 55, in download
    get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\core\fetching.py", line 121, in get_remote_file
    _fetch_file(url, filename)

  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\core\fetching.py", line 177, in _fetch_file
    os.path.basename(file_name))

OSError: Unable to download 'ffmpeg.win32.exe'. Perhaps there is a no internet connection? If there is, please report this problem.

```

**Comment by peircej** [comment]
> I consider this a bug, as we always forcefully try to download ffmpeg / use the downloaded version, without checking whether a version is already installed. 

Actually the download() function in `imageio` is designed to check for ffmpeg first (using its arg `force_download=False`):
https://github.com/imageio/imageio/blob/1d4e4fc532eb908bc57e046b04945ef7fdfd9af2/imageio/plugins/ffmpeg.py#L51

The problem, apparently, is that this doesn't detect the conda-installed ffmpeg

**Comment by hoechenberger** [comment]
> Actually the download() function in `imageio` is designed to check for ffmpeg first (using its arg `force_download=False`):

Yes and no: what they call a "local copy" is a *their* copy of an ffmpeg binary in the appdata directory ([see `imageio.core.get_remote_file()`](https://github.com/imageio/imageio/blob/1d4e4fc532eb908bc57e046b04945ef7fdfd9af2/imageio/core/fetching.py#L43), which get's called by `download()`)
It would never check e.g. for a system-wide installed ffmpeg, and adheres to the naming scheme the  `imageio` authors came up with. So by invoking `download()`, we _always_ override existing installations of ffmpeg, unless the `IMAGEIO_FFMPEG_EXE` environment variable is set (which then takes precedence).

**Comment by tjwilli58** [comment]
Even when I have IMAGEIO_FFMPEG_EXE set, download() tries to download.


```
Python 3.6.4 |Anaconda custom (64-bit)| (default, Mar 12 2018, 20:20:50) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, imageio
>>> os.environ['IMAGEIO_FFMPEG_EXE']
'C:\\Users\\timothy.j.williams1\\Anaconda3\\Library\\bin\\ffmpeg.exe'
>>> imageio.plugins.ffmpeg.get_exe()
'C:\\Users\\timothy.j.williams1\\Anaconda3\\Library\\bin\\ffmpeg.exe'
>>> imageio.plugins.ffmpeg.download()
Imageio: 'ffmpeg.win32.exe' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine active
ly refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine active
ly refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine active
ly refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine active
ly refused it>.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\plugins\ffmpeg.py", lin
e 55, in download
    get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\core\fetching.py", line
 121, in get_remote_file
    _fetch_file(url, filename)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio-2.1.2-py3.6.egg\imageio\core\fetching.py", line
 177, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg.win32.exe'. Perhaps there is a no internet connection? If there is, please report th
is problem.
>>>

```

**Comment by tjwilli58** [comment]
Also

```
>>> imageio.plugins.ffmpeg.download(force_download=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: download() got an unexpected keyword argument 'force_download'

```

**Comment by hoechenberger** [comment]
> Even when I have IMAGEIO_FFMPEG_EXE set, download() tries to download.

What is it pointing to?

> TypeError: download() got an unexpected keyword argument 'force_download'

Well the kwarg is certainly present in `imageio` 2.3.0. Which version are you using?

**Comment by tjwilli58** [comment]
I had imageio 2.1.2 this morning when I posted that. I've since updated to 2.3.0, but although the argument is recognized, the download is still attempted.

```
Python 3.6.4 |Anaconda custom (64-bit)| (default, Mar 12 2018, 20:20:50) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os,imageio
>>> os.environ['IMAGEIO_FFMPEG_EXE']
'C:\\Users\\timothy.j.williams1\\Anaconda3\\Library\\bin\\ffmpeg.exe'
>>> imageio.__version__
'2.3.0'
>>> imageio.plugins.ffmpeg.get_exe()
'C:\\Users\\timothy.j.williams1\\Anaconda3\\Library\\bin\\ffmpeg.exe'
>>> imageio.plugins.ffmpeg.download(force_download=False)
Imageio: 'ffmpeg-win32-v3.2.4.exe' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>.
Error while fetching file: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio\plugins\ffmpeg.py", line 73, in download
    force_download=force_download)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio\core\fetching.py", line 127, in get_remote_file
    _fetch_file(url, filename)
  File "C:\Users\timothy.j.williams1\Anaconda3\lib\site-packages\imageio\core\fetching.py", line 183, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg-win32-v3.2.4.exe'. Perhaps there is a no internet connection? If there is, please report this problem.
>>>

```

**Comment by tjwilli58** [comment]
Just in case there's a question of version mismatch:

```
PS L:\> C:\Users\timothy.j.williams1\Anaconda3\Library\bin\ffmpeg.exe -version
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.0 (GCC)
configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv
 --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enab
le-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp -
-enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-li
bvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2
 --enable-avisynth
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
PS L:\>

```

**Comment by tjwilli58** [comment]
Did a 

`conda.exe install ffmpeg=3.2.4 -c conda-forge`

so the versions would match. Same result

**Comment by hoechenberger** [comment]
Like I said, `download()` will _always_ download unless a download had been successful previously. So everything is behaving as expected.

**Comment by tjwilli58** [comment]
So what's the point of force_download=False ?

**Comment by tjwilli58** [comment]
Never mind. force_download=True means download even if it's found.

**Comment by hoechenberger** [comment]
It will download even if a previously downloaded version has been found. But this is really getting a bout out of hand here, the issues you are now discussing are not related to PsychoPy, but to `imageio`; we cannot know how their design decisions came about.

**Comment by tjwilli58** [comment]
I'm glad to see you changed the code in _psychopyApp.py. Thanks. So I suppose this issue can be closed?

**Comment by hoechenberger** [comment]
No, it's not merged yet and I don't know if it will. We need to see whether the changes create new kinds of trouble ;)

**Comment by tjwilli58** [comment]
I hope it gets merged. I changed my copy to what you suggested.

**Comment by hoechenberger** [comment]
Let me know if it works for you. Be sure to install ffmpeg and imageio before trying this out.

**Comment by peircej** [comment]
I am intending to merge this in, yes. I was just delaying while I tried to work out the current problem with the test suite (that Travis system python has stopped working for unrelated reasons)
