### ISSUE TITLE
[Bug]: When there's an "untitled.psyexp" saved in the working directory, opening the Builder opens a file dialog instead of making a new "untitled.psyexp"

### ISSUE THREAD

**Issue by aforren1** [psychopy/psychopy#7349]
### PsychoPy Version

2025.2.0 (release branch)

### What OS are your PsychoPy running on?

Linux-based systems

### Bug Description

When opening a "new" Builder window (e.g. with `psychopy --builder` or by clicking the "New: create new experiment file" button with a Builder window open) , I'm prompted to open an existing .psyexp file instead of getting a blank "untitled.psyexp".  If I choose an existing .psyexp, that opens fine.

If I close/cancel opening an existing file at that point, I get the following exception:

```
Traceback (most recent call last):
  File "/home/bwadmin/psychopy/psychopy/app/_psychopyApp.py", line 862, in newBuilderFrame
    self.builder = BuilderFrame(None, -1,
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bwadmin/psychopy/psychopy/app/builder/builder.py", line 215, in __init__
    self.updateReadme()  # check/create frame as needed
    ^^^^^^^^^^^^^^^^^^^
  File "/home/bwadmin/psychopy/psychopy/app/builder/builder.py", line 1009, in updateReadme
    self.readmeFrame.setFile(None)
  File "/home/bwadmin/psychopy/psychopy/app/builder/builder.py", line 3467, in setFile
    self.expName = self.parent.exp.getExpName()
                   ^^^^^^^^^^^^^^^
AttributeError: 'BuilderFrame' object has no attribute 'exp'
```

### Expected Behaviour

I expect to get a blank "untitled.psyexp" by default?

### Steps to Reproduce

1. `psychopy --builder`
2. Click cancel or X button

### Additional context

I have 0fe2019bd77b5744c34d6d6220ca7764daf8a067 installed in a virtual environment with Python 3.11 on Debian 12 + X11 + Xfce. I've also tried deleting the `~/.psychopy3` folder, with no difference in behavior. I cannot reproduce on Windows with Py3.11 + the same commit.

**Comment by aforren1** [comment]
Actually, I *can* reproduce on Windows. The issue happens when there's an "untitled.psyexp" file already saved in the working directory. `git bisect` tells me this was introduced in d3ff51677b383646f0a0cb15d0b520e1e6d13f9f

**Comment by TEParsons** [comment]
I think I know why this is; the problem is these lines:
```
if self.filename.is_file():
            self.fileOpen(filename=fileName, closeCurrent=False)
```

if `fileName` is `None`, then `self.filename` is `untitled.psyexp`. Usually this is fine because just `untitled.psyexp` with no path won't exist, but if there's a file with that name in the root of the app's Python process' cwd then there's a discrepancy (`self.filename.is_file()` is `True` but `fileName is not None` is `False`) which leads to the behaviour you're seeing.

Adding a check for `fileName is not None` fixes this - will put in a PR :)

**Comment by aforren1** [comment]
Thanks, looks like that works for me!
