### ISSUE TITLE
Tests fail with `AttributeError: module 'pytest' has no attribute 'app'`

### ISSUE THREAD

**Issue by TheChymera** [psychopy/psychopy#2841]
I am trying to run the test suite on the latest release (`2020.1.3`) with:

```
pytest -v -s -m "not needs_sound" psychopy
```

And I get the following test failure:

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pytest", line 11, in <module>
    load_entry_point('pytest==5.4.1', 'console_scripts', 'pytest')()
  File "/usr/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 125, in main
    config=config
  File "/usr/lib64/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib64/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib64/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib64/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib64/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib64/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib64/python3.6/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib64/python3.6/site-packages/_pytest/main.py", line 229, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/usr/lib64/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib64/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib64/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib64/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib64/python3.6/site-packages/_pytest/terminal.py", line 716, in pytest_sessionfinish
    outcome.get_result()
  File "/usr/lib64/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib64/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/var/tmp/portage/sci-biology/psychopy-2020.1.3/work/psychopy-2020.1.3/psychopy/tests/conftest.py", line 14, in pytest_sessionfinish
    pytest.app.quit()
AttributeError: module 'pytest' has no attribute 'app'
```

This being the full [build.log](https://github.com/psychopy/psychopy/files/4391278/build.log).

Is this maybe another missing dep, as in https://github.com/psychopy/psychopy/issues/2840 ?

**Comment by hoechenberger** [comment]
[Currently](https://github.com/psychopy/psychopy/blob/36dc96223f614b3e71fc75d583c62a20d4d3bae1/travis/environment-3.8.yml#L45) the test suite only works with pytest <4.1. PRs to change this are welcome!
