### ISSUE TITLE
AttributeError: 'SoundPTB' object has no attribute 'isFinished'

### ISSUE THREAD

**Issue by frankgasking** [psychopy/psychopy#5537]
In the latest release: v2023.1.2 , the default sound library is PTB, and when using the builder sound component to run a WAV file, you get the following error message:

`AttributeError: 'SoundPTB' object has no attribute 'isFinished'`

This is tested on Windows 10, and after uninstalling and re-installing to double check.

Doesn't complain about ".status" or ".isPlaying" attributes that is also generated upon running the builder script.   I've not yet tested in v2023 versions prior. I can confirm that it is working fine in v2022.1.3 (which is the version we're fixed on for this academic year).

**EDIT:** Just tested in v2023.1.1 and no errors.
